import fs from 'fs';
import path from 'path';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const runtime=read('runtime-current.js');
const html=read('index.html');
const sw=read('sw.js');
const master=read('docs/MASTER_SPEC.md');
const checks=[];
function check(name,cond){checks.push([name,!!cond]);if(!cond)process.exitCode=1}
check('Phase 4 config pipeline',runtime.includes('Phase 4 — canonical plan / partner ExerciseConfig pipeline'));
check('Unique plan-name guard',runtime.includes('duplicatePlanNameV31')&&runtime.includes('nextUniquePlanNameV31'));
check('Duplicate action uses unique name',html.includes('rethinkNextUniquePlanNameV31'));
check('0:00 pause runtime rule',master.includes('0:00 Pause ist ein gültiger persistenter Wert')&&!/rest\s*\|\|\s*90/.test(runtime)&&runtime.includes('Number.isFinite(Number(lead.rest))?Number(lead.rest):0'));
check('Single recommendation phase',master.includes('Genau eine Empfehlung pro Übung')&&runtime.includes('function injectRecommendationsV31()')&&runtime.includes('card.querySelectorAll(".recommendation,.live-recommendation,.live-recommendations-unit").forEach(n=>n.remove())')&&runtime.includes('unit.members.map((x,memberIndex)=>'));
check('Keyboard manager phase',master.includes('Tastatur bleibt während echter Eingabe geöffnet')&&runtime.includes('Phase 10 — canonical keyboard/input manager')&&runtime.includes('inputMutationDepth>0&&focused?.matches?.(LIVE_INPUT)')&&runtime.includes('Focus + blur with no input is a strict no-op')&&runtime.includes("visualViewport.addEventListener('resize',syncKeyboardState,true)"));
check('6h PWA resume policy',master.includes('innerhalb von 6 Stunden'));
check('Catalog translation protection',runtime.includes('function p6ProtectCatalogOriginals')&&runtime.includes('(e?.variants||[]).forEach(v=>terms.add(String(v)))')&&runtime.includes('(e?.equipment||[]).forEach(v=>terms.add(String(v)))')&&runtime.includes('if(p6Lang()!=="en"||p6IsCatalogOriginal(text))return text')&&master.includes('Übungsnamen, Varianten und Hilfsmittel/Equipment bleiben immer im englischen Original und werden nicht übersetzt'));
check('Push mounts into settingsBody',runtime.includes("document.getElementById('settingsBody')"));
check('No undefined renderSettings hook',!runtime.includes('window.renderSettings||renderSettings'));
check('Push uses real settings flow',runtime.includes('priorOpenSettingsPush=window.openSettingsPage||openSettingsPage'));
check('SW release cache',sw.includes('rethink-fitness-20260827-release1'));
check('SW correct notification icon',sw.includes("icon:'./icons/icon-192.png'")&&sw.includes("badge:'./icons/icon-192.png'"));
check('SW has no phantom README/AUDIT precache',!sw.includes("'./README.md'")&&!sw.includes("'./AUDIT.md'"));
check('Runtime release URL aligned',html.includes('runtime-current.js?v=20260827r1')&&sw.includes('runtime-current.js?v=20260827r1'));
const assetMatches=[...sw.matchAll(/'\.\/([^']+)'/g)].map(m=>m[1].split('?')[0]).filter(x=>x&&x!=='');
for(const asset of new Set(assetMatches)) check('Asset exists: '+asset,fs.existsSync(path.join(root,asset)));
const ok=checks.every(x=>x[1]);
for(const [n,v] of checks)console.log(`${v?'PASS':'FAIL'} ${n}`);
console.log(`\n${checks.filter(x=>x[1]).length}/${checks.length} checks passed`);
if(!ok)process.exit(1);
